### ISSUE TITLE
Use Numpad instead of Keyboard when typing in bib numbers on iPad

### ISSUE THREAD

**Issue by mattave** [RunSignUp-Team/RunSignup-Mobile-Timing-App#68]
Requested by Matt Sinclair:

> I was helping Crisp this weekend at a race and if using the app on an iPad during the backup finish line mode when you are keying in bib numbers it gives you the full keyboard on an iPad instead of just the number pad. Is that something that is easy to update? I ended up using my iPhone as that only gave the number pad for entry.

**Comment by nathanael-rsu** [comment]
This is an iPad limitation that we have no control over -- the iPad has no number pad, presumably because Apple felt that it was a waste of space to not give you other characters as well. So all we can do is show the full keyboard with the numbers.
![IMG_E5798CD04FE2-1](https://user-images.githubusercontent.com/97470828/196434020-1be3b487-6e75-46bd-9a69-21446a4bb73a.jpeg)

**Comment by mattave** [comment]
Thanks @nathanael-rsu that makes sense
